<a href="https://colab.research.google.com/github/darapanenichandana/my-app/blob/main/Slab1(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

def get_matrix_input(prompt):
    print(prompt)
    rows = int(input("Enter the number of rows: "))
    cols = int(input("Enter the number of columns: "))
    print(f"Enter the elements row-wise (space-separated):")
    matrix = []
    for _ in range(rows):
        row = list(map(float, input().split()))
        if len(row) != cols:
            print("Invalid number of elements. Try again.")
            return get_matrix_input(prompt)
        matrix.append(row)
    return np.array(matrix)

def display_menu():
    print("\nMatrix Operations Tool")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Transpose")
    print("5. Determinant")
    print("6. Exit")

def main():
    while True:
        display_menu()
        choice = input("Choose an operation (1-6): ")

        if choice in ['1', '2', '3']:
            matrix1 = get_matrix_input("Enter the first matrix:")
            matrix2 = get_matrix_input("Enter the second matrix:")

            if choice == '1':
                if matrix1.shape == matrix2.shape:
                    result = matrix1 + matrix2
                    print("Result of Addition:")
                else:
                    print("Matrices must have the same dimensions for addition.")
                    continue

            elif choice == '2':
                if matrix1.shape == matrix2.shape:
                    result = matrix1 - matrix2
                    print("Result of Subtraction:")
                else:
                    print("Matrices must have the same dimensions for subtraction.")
                    continue

            elif choice == '3':
                if matrix1.shape[1] == matrix2.shape[0]:
                    result = np.dot(matrix1, matrix2)
                    print("Result of Multiplication:")
                else:
                    print("Number of columns in the first matrix must equal the number of rows in the second matrix.")
                    continue

            print(result)

        elif choice == '4':
            matrix = get_matrix_input("Enter the matrix to transpose:")
            result = np.transpose(matrix)
            print("Transpose of the matrix:")
            print(result)

        elif choice == '5':
            matrix = get_matrix_input("Enter the square matrix to find the determinant:")
            if matrix.shape[0] == matrix.shape[1]:
                det = np.linalg.det(matrix)
                print(f"Determinant of the matrix: {det}")
            else:
                print("Determinant can only be calculated for square matrices.")

        elif choice == '6':
            print("Exiting the Matrix Operations Tool. Goodbye!")
            break

        else:
            print("Invalid choice. Please select a valid option.")

if __name__ == "__main__":
    main()



Matrix Operations Tool
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit
Choose an operation (1-6): 1
Enter the first matrix:
Enter the number of rows: 3
Enter the number of columns: 3
Enter the elements row-wise (space-separated):
1 6 7
6 8 9
4 5 6
Enter the second matrix:
Enter the number of rows: 3 
Enter the number of columns: 3
Enter the elements row-wise (space-separated):
8 9 7
4 5 6
2 3 4
Result of Addition:
[[ 9. 15. 14.]
 [10. 13. 15.]
 [ 6.  8. 10.]]

Matrix Operations Tool
1. Addition
2. Subtraction
3. Multiplication
4. Transpose
5. Determinant
6. Exit
Choose an operation (1-6): 2
Enter the first matrix:
Enter the number of rows: 2
Enter the number of columns: 2
Enter the elements row-wise (space-separated):
4 5
7 8
Enter the second matrix:
Enter the number of rows: 2
Enter the number of columns: 2
Enter the elements row-wise (space-separated):
6 7
4 5
Result of Subtraction:
[[-2. -2.]
 [ 3.  3.]]

Matrix Operations Tool
1. Addition
2. Subtra